name: 'Build and publish python package'
description: 'Build and publish python package'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - shell: bash
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        echo "$TWINE_PASSWORD"
