name: 'Build and publish python package'
description: 'Build and publish python package'

inputs:
  password:
    description: 'TWINE_PASSWORD/PYPI_API_TOKEN'
    required: true

  version:
    description: 'python version'
    required: false
    default: '3.9'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Set up Python ${{ inputs.version }}"
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.version }}

    - name: "Install pypa/build"
      run: |
        python -m pip install build --user
      shell: bash

    - name: "Build a binary wheel and a source tarball"
      run: |
        python -m build --sdist --wheel --outdir dist/ .
      shell: bash

    - name: "Publish distribution 📦 to PyPI"
      # TODO: if public repo
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ inputs.password }}
