name: 'Delete versions 📦 from PyPI'
description: 'Delete versions 📦 from PyPI'

inputs:
  keep:
    description: 'Release: keep'
    required: false
    default: '3'

  pypi_password:
    description: 'PyPi: password (PYPI_CLEANUP_PASSWORD)'
    required: true

  pypi_user:
    description: 'PyPi: user'
    required: true
    default: ${{ github.actor }}

runs:
  using: "composite"
  steps:
    - name: "Delete distribution 📦 from PyPI"
      run: |
        if [ -f setup.cfg ]; then
          sudo python -m pip install --quiet pypi-cleanup
          NAME="$(sed 's/ //g' setup.cfg | awk -F '=' '/^name=/ { print $2 }')"
          for i in $(curl -sGL https://pypi.org/pypi/${NAME}/json | jq -r '.releases | keys[] as $k | $k' | \
              sort -V | head -n -${{ inputs.keep }}); do 
            pypi-cleanup -u ${{ inputs.pypi_user}} -p ${NAME} --do-it --yes -r ${i}
          done
        fi
        echo '::echo::on'
        echo "::set-output name=NAME::${NAME}"
        echo "::set-output name=VERSIONS::${VERSIONS}"
      shell: bash
      env:
        PYPI_CLEANUP_PASSWORD: ${{ inputs.pypi_password }}
      if: ${{!github.event.repository.private}}
