name: "GitHub repository description"
description: "GitHub repository description"

branding:
  icon: "bookmark"
  color: "orange"

inputs:
  repository:
    description: 'GitHub: user/name'
    required: false
    default: ${{ github.repository }}

outputs:
  DESCRIPTION:
    description: "GitHub: description"
    value: ${{ steps.DESCRIPTION.outputs.DESCRIPTION }}

runs:
  using: "composite"
  steps:
      - name: "GitHub: description"
        id: DESCRIPTION
        run: |
          echo "::set-output name=DESCRIPTION::$(curl -fsL -H "Accept: application/vnd.github.v3+json" \
           -H 'Authorization: token ${{ github.token }}' \
           https://api.github.com/repos/${{ inputs.repository }} | jq -r .description)"
        shell: bash
