name: "GitHub repository description"
description: "GitHub repository description"

branding:
  icon: "bookmark"
  color: "orange"

inputs:
  repository:
    description: 'GitHub: user/name'
    required: false
    default: ${{ github.repository }}

outputs:
  DESCRIPRION:
    description: "GitHub: description"
    value: ${{ steps.DESCRIPRION.outputs.DESCRIPRION }}

runs:
  using: "composite"
  steps:
      - run: |
          curl -fsL -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ inputs.repository }} | jq -r .description
        shell: bash

      - name: "GitHub: description"
        id: DESCRIPRION
        run: |
          echo "::set-output name=DESCRIPRION::$(curl -fsL -H "Accept: application/vnd.github.v3+json" \
           -H 'Authorization: token ${{ github.token }}' \
           https://api.github.com/repos/${{ inputs.repository }} | jq -r .description)"
        shell: bash
