name: "GitHub ID"
description: "GitHub ID"

branding:
  icon: "user-check"
  color: "cyan"

inputs:
  user:
    description: 'GitHub: user'
    required: false
    default: ${{ github.actor }}

outputs:
  ID:
    description: "GitHub: ID"
    value: ${{ steps.ID.outputs.ID }}

runs:
  using: "composite"
  steps:
      - name: "GitHub: ID"
        id: ID
        run: |
          echo "::set-output name=ID::$(curl -fsL -H "Accept: application/vnd.github.v3+json" \
            -H 'Authorization: token ${{ github.token }}' \
            https://api.github.com/users/${{ inputs.user }} | jq -r .id)"
        shell: bash
