name: "Release"
description: "release"

branding:
  icon: "activity"
  color: "orange"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ env.GH_TOKEN }}


