name: tag
description: "Tag and push repository if 'svu current' != 'svu next'"

branding:
  icon: "tag"
  color: "green"

outputs:
  updated:
    description: "Version: Updated"
    value: ${{ steps.VERSION.outputs.CURRENT }}

  version:
    description: "Version"
    value: ${{ steps.svu.outputs.version }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: ${{ inputs.repository }}
        token: ${{ env.GITHUB_TOKEN }}

    - name: "svu: ubuntu"
      run: |
        echo 'deb [trusted=yes] https://apt.fury.io/caarlos0/ /' | \
          sudo tee /etc/apt/sources.list.d/caarlos0.list >/dev/null
        sudo apt update -qq &>/dev/null
        sudo apt install -qq svu &>/dev/null
      shell: bash
      if: github.ref_type == 'branch' && runner.os == 'Linux'

    - name: "svu: macOS"
      run: |
        brew update --quiet >/dev/null
        brew install --quiet caarlos0/tap/svu >/dev/null
      shell: bash
      if: github.ref_type == 'branch' && runner.os == 'macOS'

    - name: "Version"
      id: VERSION
      run: |
        CHANGED=false
        PREFIX='v'
        [ "${{ inputs.strip }}" != 'true' ] || { flag='--strip-prefix'; PREFIX=''; }
        CURRENT=$(svu ${flag} current)
        NEXT=$(svu ${flag} next)
        [ "${CURRENT}" = "${NEXT}" ] || CHANGED=true
        echo '::echo::on'
        echo "::set-output name=CHANGED::${CHANGED}"
        echo "::set-output name=CURRENT::${CURRENT}"
        echo "::set-output name=NEXT::${NEXT}"
        echo "::set-output name=PREFIX::${PREFIX}"
      shell: bash
      if: github.ref_type == "branch"

    - name: "Tag & push"
      run: |
        git tag ${{ steps.VERSION.outputs.NEXT }}
        git push origin ${{ steps.VERSION.outputs.NEXT }}
      shell: bash
      if: github.ref_type == 'branch' && steps.VERSION.outputs.CHANGED == 'true'

    - name: "Release: create"
      id: create
      uses: softprops/action-gh-release@v1
      with:
        repository: ${{ inputs.repository }}
        tag_name: ${{ steps.VERSION.outputs.NEXT }}
      if: github.ref_type == 'branch' && steps.VERSION.outputs.CHANGED == 'true'

    - name: "Release: delete"
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: ${{ inputs.keep }}
        delete_tags: true
        repo: ${{ inputs.repository }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      if: inputs.release == 'true' && steps.VERSION.outputs.CHANGED == 'true'
