name: "Brew Tap Release"
description: "Brew Tap Release"

branding:
  icon: "activity"
  color: "orange"

inputs:
  homebrew_owner:
    description: "The name of the homebrew tap owner to publish your formula to as it appears on GitHub."
    required: false
    default: ${{ github.actor }}

  homebrew_tap:
    description: "The name of the homebrew tap to publish your formula to as it appears on GitHub."
    required: false
    default: "dev"

  formula_folder:
    description: "The name of the folder in your homebrew tap where formula will be committed to."
    required: true
    default: "Formula"

  github_token:
    description: "The GitHub Token that has `repo` permissions for the homebrew tap you want to release to."
    required: true

  commit_owner:
    description: "Git author info used to commit to the homebrew tap."
    required: false
    default: ${{ github.workflow }}

  commit_email:
    description: "Git author info used to commit to the homebrew tap."
    required: false
    default: "63794670+${{ github.workflow }}@users.noreply.github.com"

  depends_on:
    description: "Custom dependencies in case other formulas are needed to build the current one (can be multiline)."
    required: false

  install:
    description: "Custom install command for your formula."
    required: true

  test:
    description: "Custom test command for your formula so you can run `brew test`."
    required: false

  skip_commit:
    description: "Skips committing the generated formula to a homebrew tap (useful for local testing)."
    required: false

  update_readme_table:
    description: "Update your homebrew tap's README with a table of all projects in the tap."
    required: false
    default: 'true'

  debug:
    description: "Logs debugging info to console."
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ inputs.homebrew_owner }}/homebrew-${{ inputs.homebrew_tap }}
        fetch-depth: 0
        token: ${{ inputs.github_token }}

    - uses: fregante/setup-git-user@v1

    - name: "Create Formula"
      run: |
        if [ ! -d ${{ inputs.formula_folder }} ]; then 
          mkdir ${{ inputs.formula_folder }}
          git add ${{ inputs.formula_folder }}
          git commit -a -m "${{ github.workflow }}"
          git push 
        fi
        file=${{ inputs.formula_folder }}/${{ github.event.repository.name }}.rb
        if [ ! -f ${file} ]; then 
          touch ${file}
          git add ${file}
          git commit -a -m ${file}
          git push 
        fi
      shell: bash

    - uses: Justintime50/homebrew-releaser@v1
      with:
        homebrew_owner: ${{ inputs.homebrew_owner }}
        homebrew_tap: homebrew-${{ inputs.homebrew_tap }}
        formula_folder: ${{ inputs.formula_folder }}
        github_token: ${{ inputs.github_token }}
        commit_owner: ${{ inputs.commit_owner }}
        commit_email: ${{ inputs.commit_email }}
        depends_on: ${{ inputs.depends_on }}
        install: ${{ inputs.install }}
        test: ${{ inputs.test }}
        skip_commit: ${{ inputs.skip_commit }}
        update_readme_table: ${{ inputs.update_readme_table }}
        debug: ${{ inputs.debug }}
