#!/usr/bin/env bash

set -eu
shopt -s inherit_errexit

#######################################
# update workflow
# Arguments:
#  1    tap owner
#######################################
workflow() {
  local depends formula="${0##*/}" repo tmp
  repo="homebrew-${formula}"
  git -C /tmp clone --quiet "git://github.com/${repo}/${formula}.git"

  depends="$(find "/tmp/${repo}/Formula" -type f -name "*.rb" -not -name "${formula}.rb"\
    -exec basename "{}" .rb \; | sed "s|^|\"${1}/${formula}/|g;s|$|\"|g")"
    
  cd "$(git rev-parse --show-toplevel)"
  test -d .github/workflows || mkdir -p .github/workflows

  tmp="$(mktemp)"
  cat > "${tmp}" <<EOF
name: main

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - id: TAG
        uses: j5pu/actions/tag@main
      - uses: j5pu/actions/tap@main
        with:
          github_token: \${{ secrets.TOKEN }}
          depends_on: |
$(for i in ${depends}; do echo "            ${i}"; done)
          install: |
            bin.install homebrew-${formula}
          test: |
            system "#{HOMEBREW_PREFIX}/bin/homebrew-${formula}"

EOF
  if ! cmp --quiet "${tmp}" .github/workflows/main.yaml 2>/dev/null; then
    echo Changed: "${PWD}/.github/workflows/main.yaml"
    mv "${tmp}" .github/workflows/main.yaml
  fi
}

#######################################
# updates dev formula in homebrew-dev with all formulas when a formula has changed. It is executed on GitHub.
# Arguments:
#  1    tap owner
#######################################
main() {
  [ "${GITHUB_RUN_ID-}" ] || exit 0
  >&2 echo Starting: "$0"
  workflow "$@"
}

main "$@"
