#!/usr/bin/env bash

set -eu
shopt -s inherit_errexit

#######################################
# update workflow
# Globals:
#   depends
#   {
# Arguments:
#  None
#######################################
workflow() {
  local depends formula="${0##*/}" tmp
  cd "$1"
  depends="$(find "${2}/Formula" -type f -name "*.rb" -not -name "${formula}.rb"\
    -exec basename "{}" .rb \; | sed "s|^|\"${3}/${formula}/|g;s|$|\"|g")"
    
  cd "$(git rev-parse --show-toplevel)"
  test -d .github/workflows || mkdir -p .github/workflows

  tmp="$(mktemp)"
  cat > "${tmp}" <<EOF
name: main

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  GITHUB_TOKEN: \${{ secrets.TOKEN }}

jobs:
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - id: TAG
        uses: j5pu/actions/tag@main
      - uses: j5pu/actions/tap@main
        with:
          github_token: \${{ secrets.TOKEN }}
          depends_on: |
$(for i in ${depends}; do echo "            ${i}"; done)
          install: |
            bin.install homebrew-${formula}
          test: |
            system "#{HOMEBREW_PREFIX}/bin/homebrew-${formula}"

EOF
  if ! cmp --quiet "${tmp}" .github/workflows/main.yaml 2>/dev/null; then
    >&2 echo Changed: "${PWD}/.github/workflows/main.yaml"
    mv "${tmp}" .github/workflows/main.yaml
    git config --global user.email "$5"
    git config --global user.name "$6"
    git add .github/workflows/main.yaml
    git commit --quiet -a -m "$4"
    git push --quiet
  fi
}

#######################################
# updates dev formula in homebrew-dev with all formulas when a formula has changed. It is executed on GitHub.
# Arguments:
#  1    dev repository path
#  2    homebrew-dev repository path
#  3    tap owner
#  4    message
#  5    email
#  6    name
#######################################
main() {
  [ "${GITHUB_RUN_ID-}" ] || exit 0
  >&2 echo Starting: "$0"
  workflow "$@"
}

main "$@"
