name: description

on:
  workflow_dispatch:

jobs:
  id:
    runs-on: ubuntu-latest
    steps:
      - id: DESCRIPTION
        uses: j5pu/actions/description@main
      - run: echo ${{ steps.DESCRIPTION.outputs.DESCRIPTION }}
