name: secrets

on:
  workflow_dispatch:

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: j5pu/actions/secrets@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
