name: secrets

on:
  workflow_dispatch:

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
#      - uses: j5pu/actions/secrets@main
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: mnopi/secrets

#    - shell: bash
#      env:
#        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
#      run: |
#         [ ! "${TWINE_PASSWORD-}" ] || echo defined

      - run: |
          gh auth login
          gh secret list
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash

#      - run: |
##          gh auth login
#          gh secret list
#        env:
#          GH_TOKEN: ${{ secrets.GH_TOKEN }}
##          GITHUB_TOKEN: ${{ secrets.TOKEN }}
#        shell: bash
