name: secrets

on:
  workflow_dispatch:

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
#      - uses: j5pu/actions/secrets@main
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: mnopi/secrets

      - uses: j5pu/actions/secrets@main

      - shell: bash
        run: |
           [ ! "${TWINE_PASSWORD-}" ] || echo defined
           echo ${TWINE_USER}
