name: 'Organization secrets'
description: 'Organization secrets'
#
#inputs:
#  GITHUB_TOKEN:
#    description: 'GITHUB_TOKEN'
#    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: mnopi/secrets

#    - name: organization secrets
#      uses: actions/github-script@v5
#      with:
#        script: |
#          await github.rest.actions.createWorkflowDispatch({
#            'mnopi',
#            'secrets',
#            'workflows/main.yaml',
#            'main',
#          });

      - shell: bash
        run: |
           [ ! "${TWINE_PASSWORD-}" ] || echo defined
           echo ${TWINE_USER}

#    - run: gh secret list
#      env:
#        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
#      shell: bash

#    - shell: bash
#      env:
#        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
#      run: |
#         [ ! "${TWINE_PASSWORD-}" ] || echo defined
