name: 'Organization secrets'
description: 'Organization secrets'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: mnopi/secrets

    - shell: bash
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
         [ ! "${TWINE_PASSWORD-}" ] || echo defined
