name: 'Append secrets repository to $GITHUB_ENV'

description: 'Append secrets repository to $GITHUB_ENV'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: j5pu/secrets
        path: secrets
        fetch-depth: 0

    - name: pwd
      run: pwd
      shell: bash

    - name: ls secrets
      run: ls secrets/secrets
      shell: bash

    - name: append secrets
      run: |
        grep "^export " secrets/secrets | grep -v GITHUB_TOKEN >> $GITHUB_ENV
      shell: bash

    - name: test TWINE_PASSWORD defined
      run: |
        [ "${{ env.TWINE_PASSWORD }}" = '' ] || echo defined
      shell: sh
